### ISSUE TITLE
RuntimeError: Cowardly refusing to serialize non-leaf tensor which requires_grad

### ISSUE THREAD

**Issue by luoshmg** [NINAnor/rare_species_detections#14]
The original fine_tune.sh runs well. But when I change `--trainer.gpus 1` to `--trainer.gpus 4` since I have 4 gpus, I get the error:

Traceback (most recent call last):
  File "fine_tune/trainer.py", line 31, in <module>
    cli_main()
  File "fine_tune/trainer.py", line 25, in cli_main
    MyLightningCLI(
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/cli.py", line 358, in __init__
    self._run_subcommand(self.subcommand)
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/cli.py", line 670, in _run_subcommand
    fn(**fn_kwargs)
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 608, in fit
    call._call_and_handle_interrupt(
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/trainer/call.py", line 36, in _call_and_handle_interrupt
    return trainer.strategy.launcher.launch(trainer_fn, *args, trainer=trainer, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/strategies/launchers/multiprocessing.py", line 113, in launch
    mp.start_processes(
  File "/usr/local/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 189, in start_processes
    process.start()
  File "/usr/local/lib/python3.8/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/usr/local/lib/python3.8/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/usr/local/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/usr/local/lib/python3.8/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/usr/local/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 47, in _launch
    reduction.dump(process_obj, fp)
  File "/usr/local/lib/python3.8/multiprocessing/reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
  File "/usr/local/lib/python3.8/site-packages/torch/multiprocessing/reductions.py", line 143, in reduce_tensor
    raise RuntimeError("Cowardly refusing to serialize non-leaf tensor which requires_grad, "
RuntimeError: Cowardly refusing to serialize non-leaf tensor which requires_grad, since autograd does not support crossing process boundaries.  If you just want to transfer the data, call detach() on the tensor before serializing (e.g., putting it on the queue).

I've tried setting `num_workers=0` as in https://github.com/pyg-team/pytorch_geometric/issues/1967#issuecomment-756389405, but that doesn't work for me. 

Can anybody help? Thank you very much.

**Comment by luoshmg** [comment]
Not sure, but when I change environment `python=3.8` to `python=3.10` and run command `torchrun --nproc_per_node 4 fine_tune/trainer.py` instead of `poetry run fine_tune/trainer.py`, I finally avoid the "RuntimeError".

Though I run into another error `TypeError: MilestonesFinetuning.finetune_function() missing 1 required positional argument: 'opt_idx'`.

That's not hard to fix, just remove `opt_idx: int,` from the `finetune_function` definition in `callbacks.callbacks.MilestonesFinetuning` as in https://github.com/Lightning-AI/pytorch-lightning/issues/19119#issuecomment-1843073267.
